version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: diplomvetl-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/html:rw,cached
      - ./certs:/etc/certs
      - ./logs:/var/log/nginx
    depends_on:
      - wordpress
    restart: always
    entrypoint: nginx -g "daemon off";

  mysql:
    image: mariadb
    container_name: diplomvetl-mysql
    volumes:
       - './data/db:/var/lib/mysql:delegated'
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=vetlugin
    restart: always
    ports:
      - '3366:3366'

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diplomvetl-wordpress
    volumes:
      - ./src:/var/www/html:rw,cached
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: diplomvetl-phpmyadmin
    volumes:
      - ./config/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3336
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - '8080:80'
    links:
      - mysql:mysql

  composer:
    image: composer
    container_name: diplomvetl-composer
    working_dir: /var/www/html
    restart: 'no'
    volumes:
      - ./src:/var/www/html:rw,cached
